tunnel: 6ff42ae2-765d-4adf-8112-31c55c1551ef    # tunnel id that you created on No.6 or run command `cloudflared tunnel list` to see the id
credentials-file: /root/.cloudflared/6ff42ae2-765d-4adf-8112-31c55c1551ef.json  # path of you tunnel *.json

ingress:
  - hostname: demo.example.com
    service: http://localhost:80
  - hostname: ssh.example.com
    service: ssh://localhost:22
  - service: http_status:404