version: "3.8"
services:
  tunnel:
    image: visibilityspots/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    working_dir: /root
    user: root
    volumes:
      - cloudflare-tunnel-data:/root/.cloudflared
      - ./config.yml:/root/.cloudflared/config.yml
    networks:
      - tunnel-network

volumes:
  cloudflare-tunnel-data:
    name: cloudflare-tunnel-data

networks:
  tunnel-network:
    driver: bridge
    name: cloudflare-tunnel-network
